#!/usr/bin/env tsx
/**
 * Seed fake SOW documents in Google Drive for testing.
 *
 * Copies the SOW template into the target folder and prepends
 * fake project data so the documents are distinct and searchable.
 *
 * Prerequisites:
 *   Share https://drive.google.com/drive/folders/0ACcvqajavMiEUk9PVA
 *   with kebo-mcp-sources@kebo-mcp-sources.iam.gserviceaccount.com (Editor)
 *
 * Usage:
 *   tsx scripts/seed-test-scopes.ts
 */

import { google } from 'googleapis';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CREDENTIALS_PATH = resolve(__dirname, '../credentials/kebo-mcp-sources-12c5559e4e03.json');
const TARGET_FOLDER_ID = '0ACcvqajavMiEUk9PVA';
const TEMPLATE_FILE_ID = '1ROPUlWf27LJEF_E7gnmon4u5xqt0w5lWMLlQpLW2rGQ';

interface FakeScope {
  title: string;
  client: string;
  industry: string;
  description: string;
  technologies: string[];
  budget: string;
  timeline: string;
}

const FAKE_SCOPES: FakeScope[] = [
  {
    title: 'Acme Manufacturing – Digital Transformation Portal',
    client: 'Acme Manufacturing Co.',
    industry: 'Manufacturing',
    description:
      'Modernize a legacy ERP integration layer with a cloud-native API gateway and React-based operator dashboard. Keyhole will deliver a new data pipeline from on-prem SCADA systems to AWS, plus a real-time dashboard for plant floor operators.',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'AWS ECS', 'Terraform'],
    budget: '$240,000',
    timeline: '6 months',
  },
  {
    title: 'TechFlow Health – Patient Analytics Dashboard',
    client: 'TechFlow Health Systems',
    industry: 'Healthcare',
    description:
      'Build a clinical outcomes analytics platform that ingests HL7 FHIR data from three hospital EMR systems and surfaces actionable insights to nursing and administrative staff via a secure web portal.',
    technologies: ['Python', 'FastAPI', 'Snowflake', 'Azure', 'Power BI Embedded'],
    budget: '$175,000',
    timeline: '4 months',
  },
  {
    title: 'Bridgeport Financial – Loan Origination Automation',
    client: 'Bridgeport Financial Group',
    industry: 'Financial Services',
    description:
      'Automate the end-to-end consumer loan origination workflow by replacing a paper-based approval process with a BPMN workflow engine, reducing time-to-decision from 5 business days to under 4 hours.',
    technologies: ['Java', 'Spring Boot', 'PostgreSQL', 'Camunda BPM', 'GCP Cloud Run'],
    budget: '$320,000',
    timeline: '8 months',
  },
  {
    title: 'RetailPlex – Inventory Optimization Engine',
    client: 'RetailPlex Inc.',
    industry: 'Retail / E-Commerce',
    description:
      'Implement a real-time inventory forecasting service that integrates POS data from 120 retail locations with supplier inventory APIs to reduce stockouts by an estimated 35%.',
    technologies: ['Python', 'Apache Kafka', 'Elasticsearch', 'AWS Lambda', 'Next.js'],
    budget: '$145,000',
    timeline: '5 months',
  },
  {
    title: 'CivicBridge – Permit Management Modernization',
    client: 'CivicBridge Municipal Services',
    industry: 'Government / Public Sector',
    description:
      'Replace a 15-year-old permitting system with a citizen-facing web portal, an internal staff workflow engine, and integration with the county GIS layer for parcel-level tracking.',
    technologies: ['Vue.js', '.NET 8', 'SQL Server', 'Azure App Service', 'ArcGIS REST API'],
    budget: '$290,000',
    timeline: '9 months',
  },
  {
    title: 'Horizon Logistics – Fleet Telematics Platform',
    client: 'Horizon Logistics LLC',
    industry: 'Transportation & Logistics',
    description:
      'Design and build a telematics data platform that collects GPS/CAN-bus data from 800 long-haul trucks, processes events in near-real time, and exposes a driver-facing mobile app and dispatcher web console.',
    technologies: ['React Native', 'Go', 'TimescaleDB', 'Kafka', 'AWS IoT Core'],
    budget: '$410,000',
    timeline: '10 months',
  },
];

function buildDocHeader(scope: FakeScope): string {
  const lines = [
    `[TEST DATA — generated by seed-test-scopes.ts]`,
    ``,
    `Client: ${scope.client}`,
    `Industry: ${scope.industry}`,
    `Project: ${scope.title}`,
    ``,
    `Project Overview`,
    scope.description,
    ``,
    `Proposed Technology Stack`,
    scope.technologies.join(', '),
    ``,
    `Investment Summary`,
    `Total Estimated Budget: ${scope.budget}`,
    ``,
    `Engagement Timeline`,
    `Estimated Duration: ${scope.timeline}`,
    ``,
    `---`,
    ``,
  ];
  return lines.join('\n');
}

async function main() {
  const key = JSON.parse(readFileSync(CREDENTIALS_PATH, 'utf-8'));

  const auth = new google.auth.GoogleAuth({
    credentials: key,
    scopes: [
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/documents',
    ],
  });

  const drive = google.drive({ version: 'v3', auth });
  const docs = google.docs({ version: 'v1', auth });

  const created: string[] = [];

  for (const scope of FAKE_SCOPES) {
    process.stdout.write(`  Creating "${scope.title}" ... `);

    const copy = await drive.files.copy({
      fileId: TEMPLATE_FILE_ID,
      requestBody: {
        name: scope.title,
        parents: [TARGET_FOLDER_ID],
      },
    });

    const docId = copy.data.id!;

    // Prepend the fake metadata block at position 1 (before the template content)
    await docs.documents.batchUpdate({
      documentId: docId,
      requestBody: {
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: buildDocHeader(scope),
            },
          },
        ],
      },
    });

    const url = `https://docs.google.com/document/d/${docId}`;
    console.log(`done\n    → ${url}`);
    created.push(url);
  }

  console.log(`\nCreated ${created.length} test SOW documents in folder:`);
  console.log(`  https://drive.google.com/drive/folders/${TARGET_FOLDER_ID}`);
}

main().catch((err) => {
  console.error('\nFailed:', err.message ?? err);
  process.exit(1);
});
